runtime: ruby32
env: standard
entrypoint: bundle exec ruby pin_bot.rb

runtime_config:
    operating_system: "ubuntu22"

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1

inbound_services:
  - warmup
